import { useCallback, useEffect, useId, useRef, useState } from 'react';
import { ModusWcTextInput, ModusWcTypography } from '@trimble-oss/moduswebcomponents-react';
import StudioAiStarsIcon from './StudioAiStarsIcon';

interface StudioCanvasAiBlueprintBadgeProps {
  generatedAt?: string | null;
  prompt: string;
  onRefinePrompt?: (refinement: string) => void | Promise<void>;
}

function formatGeneratedAt(iso: string): string {
  return new Intl.DateTimeFormat(undefined, {
    dateStyle: 'medium',
    timeStyle: 'short',
  }).format(new Date(iso));
}

export default function StudioCanvasAiBlueprintBadge({
  generatedAt,
  prompt,
  onRefinePrompt,
}: StudioCanvasAiBlueprintBadgeProps) {
  const popoverId = useId();
  const containerRef = useRef<HTMLDivElement>(null);
  const refineInputRef = useRef<HTMLModusWcTextInputElement>(null);
  const closeTimeoutRef = useRef<number | null>(null);
  const [isOpen, setIsOpen] = useState(false);
  const [refinement, setRefinement] = useState('');

  const clearCloseTimeout = () => {
    if (closeTimeoutRef.current !== null) {
      window.clearTimeout(closeTimeoutRef.current);
      closeTimeoutRef.current = null;
    }
  };

  const openPopover = () => {
    clearCloseTimeout();
    setIsOpen(true);
  };

  const scheduleClose = () => {
    clearCloseTimeout();
    closeTimeoutRef.current = window.setTimeout(() => {
      setIsOpen(false);
    }, 140);
  };

  const togglePopover = () => {
    clearCloseTimeout();
    setIsOpen((current) => !current);
  };

  const handleRefineSubmit = useCallback(() => {
    const trimmed = refinement.trim();
    if (!trimmed || !onRefinePrompt) {
      return;
    }

    void onRefinePrompt(trimmed);
    setRefinement('');
    setIsOpen(false);
  }, [onRefinePrompt, refinement]);

  useEffect(() => {
    if (!isOpen) {
      return;
    }

    const handlePointerDown = (event: PointerEvent) => {
      if (!containerRef.current?.contains(event.target as Node)) {
        setIsOpen(false);
      }
    };

    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        setIsOpen(false);
      }
    };

    document.addEventListener('pointerdown', handlePointerDown);
    document.addEventListener('keydown', handleKeyDown);
    return () => {
      document.removeEventListener('pointerdown', handlePointerDown);
      document.removeEventListener('keydown', handleKeyDown);
    };
  }, [isOpen]);

  useEffect(() => {
    if (!isOpen) {
      return;
    }

    const input = refineInputRef.current?.shadowRoot?.querySelector('input');
    if (!input) {
      return;
    }

    const handleEnter = (event: KeyboardEvent) => {
      if (event.key === 'Enter') {
        event.preventDefault();
        handleRefineSubmit();
      }
    };

    input.addEventListener('keydown', handleEnter);
    return () => input.removeEventListener('keydown', handleEnter);
  }, [isOpen, handleRefineSubmit]);

  useEffect(() => () => clearCloseTimeout(), []);

  return (
    <div
      ref={containerRef}
      className="studio-canvas-ai-blueprint"
      onMouseEnter={openPopover}
      onMouseLeave={scheduleClose}
    >
      <button
        type="button"
        className="studio-canvas-ai-blueprint-badge"
        aria-expanded={isOpen}
        aria-controls={popoverId}
        aria-label="View generation details from Trimble Intelligence"
        onClick={togglePopover}
      >
        <span className="studio-canvas-ai-blueprint-badge-inner">
          <StudioAiStarsIcon className="studio-canvas-ai-blueprint-badge-icon" />
          <span className="studio-canvas-ai-blueprint-badge-label">
            Generated by Trimble Intelligence
          </span>
        </span>
      </button>

      {isOpen ? (
        <div
          id={popoverId}
          className="studio-canvas-ai-blueprint-popover"
          role="dialog"
          aria-label="Trimble Intelligence generation details"
          onMouseEnter={clearCloseTimeout}
          onMouseLeave={scheduleClose}
        >
          <div className="studio-canvas-ai-blueprint-popover-card">
            <div className="studio-canvas-ai-blueprint-popover-header">
              <ModusWcTypography hierarchy="p" size="sm" weight="semibold">
                Generated by Trimble Intelligence
              </ModusWcTypography>
              {generatedAt ? (
                <p className="studio-canvas-ai-blueprint-popover-timestamp">
                  Generated {formatGeneratedAt(generatedAt)}
                </p>
              ) : null}
            </div>

            <p className="studio-canvas-ai-blueprint-popover-transcript">{prompt}</p>

            <div className="studio-canvas-ai-blueprint-popover-refine">
              <ModusWcTextInput
                ref={refineInputRef}
                bordered
                customClass="studio-canvas-ai-blueprint-refine-input"
                disabled={!onRefinePrompt}
                enterkeyhint="go"
                inputId="studio-canvas-ai-blueprint-refine"
                placeholder="Refine this flow layout with Trimble Assist..."
                size="sm"
                value={refinement}
                onInputChange={(event: CustomEvent) => {
                  setRefinement(event.detail?.target?.value || '');
                }}
              />
            </div>
          </div>
        </div>
      ) : null}
    </div>
  );
}
